package megapublicidad2.pkg0;

import Metodos.Generales;
import java.awt.SplashScreen;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author German Valdez
 */
public class ventanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form ventanaLogin
     */
    ventanaPrincipal a;
    Generales u = new Generales();
    //Thread hilo = new Thread();

    public ventanaLogin() {
        initComponents();
        setLocationRelativeTo(null);
        txtCon.requestFocus();
    }

    public void hola() {
        labelMensajeBar.setText("Dame 5 segundos más..");
        String pass = new String(txtCon.getPassword());
        String datos[] = u.saludo(pass).split(",");
        String usu = datos[0];
        String ico = datos[1];
        a = new ventanaPrincipal(usu,ico);
        a.setVisible(true);
        this.dispose();
    }
    Thread hilo = new Thread() {
        public void run() {
            try {

                for (int i = 0; i < 98; i++) {
                    jProgressBar1.setValue(i);
                    jProgressBar1.setStringPainted(true);
                    if (i == 7) {
                        labelMensajeBar.setText("Iniciando sistema..");
                    } else if (i == 20) {
                        labelMensajeBar.setText("¿Listos para trabajar?");
                    } else if (i == 45) {
                        labelMensajeBar.setText("Cargando componentes..");
                    } else if (i == 60) {
                        labelMensajeBar.setText("Coloreando las ventanas..");
                    } else if (i == 80) {
                        labelMensajeBar.setText("Estamos por terminar..");
                    }
                    hilo.sleep(100);
                }
                hola();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMensajeBar = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        botonIngresar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtCon = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesión");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMensajeBar.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labelMensajeBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 535, 310, 20));

        jProgressBar1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 310, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoLogin.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 480, -1));

        botonIngresar.setText("Acceder");
        botonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIngresarMouseClicked(evt);
            }
        });
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 150, 50));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 150, 50));

        txtCon.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConKeyPressed(evt);
            }
        });
        getContentPane().add(txtCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 384, 245, 42));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Centro", "Allende" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 258, 245, 47));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // Boton de ingresar bueno

        String pass = new String(txtCon.getPassword());
        String tipo = jComboBox1.getSelectedItem() + "";

        if (pass.equals(u.contra(pass, tipo))) {

            hilo.start();

            // this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Contraseña incorrecta.");

            txtCon.setText("");
        }
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void txtConKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConKeyPressed
        // TODO add your handling code here:
        char car = (char) evt.getKeyCode();
        if (car == evt.VK_ENTER) {
            this.botonIngresarActionPerformed(null);
        }
    }//GEN-LAST:event_txtConKeyPressed

    private void botonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresarMouseClicked
        // TODO add your handling code here:
       /* Generales u = new Generales();

        String pass = new String(txtCon.getPassword());
        String tipo = jComboBox1.getSelectedItem() + "";

        if (pass.equals(u.contra(txtCon.getText(), tipo))) {
            a = new ventanaPrincipal(txtCon.getText());
            a.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Contraseña incorrecta.");
            txtCon.setText("");
        }*/
    }//GEN-LAST:event_botonIngresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel labelMensajeBar;
    private javax.swing.JPasswordField txtCon;
    // End of variables declaration//GEN-END:variables
}
